name: UHC
version: '${project.version}'
main: com.uhcchampions.uhc.Main
api-version: 1.8.8
description: gg
depend: [TitleAPI]
commands:
  uhc:
  pvp:
  pvpe:
  heal:
  staff:
  victory:
  gmc:
  fly:
  gms:
  release:
  healall:
  gmsp:
  w0w:
  speed:
  ban:
  kick:
  message:
    aliases: [msg]
  reply:
    aliases: [r]








