name: UHC
version: '${project.version}'
main: com.uhcchampions.uhc.Main
api-version: 1.8.8
description: gg
depend: [TitleAPI]
commands:
  uhc:
  pvp:
  pvpe:
  heal:
  staff:
    aliases: [admin]
  victory:
    aliases: [gg]
  gmc:
    aliases: [gm1]
  fly:
  gms:
    aliases: [gm2, gm0]
  public:
  private:
  healall:
  gmsp:
    aliases: [gm3]
  w0w:
  speed:
  ban:
  kick:
  crate:
  message:
    aliases: [msg]
  reply:
    aliases: [r]








